# filebeat.inputs:
# - type: log
#   paths:
#     - "/var/log/nginx/*"
#   # fields:
#   #   parser: accessLog
#   #   app: nginx
#   # fields_under_root: true

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  reload.period: 10s

filebeat.modules:
#Consumir logs del servicio de ngix
- module: nginx
  access:
    var.paths: ["/var/log/nginx/access.log*"]
  error:
    var.paths: ["/var/log/nginx/error.log*"]

#Consumir logs del sistema base
- module: system
  access:
   var.paths: ["var/log/host/system.log*"]


output.elasticsearch:
  output.elasticsearch.index: "nginx-log-%{[agent.version]}"
  setup.template.name: "nginx-log"
  setup.template.pattern: "nginx-log-%{[agent.version]}"
  hosts: ["http://elasticsearch:9200"]
  username: 'elastic'
  password: 'changeme'

processors:
  - add_host_metadata:
    when.not.contains.tags: forwarded

setup:
  kibana.host: "kibana:5601"
  dashboards.enable: true
