filebeat.inputs:
- type: log
  paths:
    - "/var/log/nginx/*"
  fields:
    parser: accessLog
    app: nginx
  fields_under_root: true

# setup:
#   kibana.host: "http://kibana:5601"
#   dashboards.enable: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: 'elastic'
  password: 'abc123'
