#We monitor any devices on the host OS. For windows and OSX this is the VM hosting docker.
packetbeat.interfaces.device: any
packetbeat.flows:
  enabled: true
  timeout: 30s
  period: 10s
packetbeat.protocols.icmp:
  enabled: true
packetbeat.protocols.dns:
  enabled: true
  ports: [53]
  include_authorities: true
  include_additionals: true
#We monitor any traffic to kibana, web, ngnix and ES
packetbeat.protocols.http:
  enabled: true
  ports: [9200, 80, 4000, 5601]
  send_headers: true
  send_all_headers: true
  split_cookie: true
  send_request: false
  send_response: false
  transaction_timeout: 10s
packetbeat.protocols.mysql:
  ports: [3306]
output.elasticsearch:
  # we use localhost because the services use host networks
  hosts: ["http://localhost:9200"]
logging.to_files: false
logging.to_files: false
