version: '2'
services:
  web:
    build: ./apollo-server-app
    command: npm run start
    volumes:
      - .:/apollo-server-app/app/
      - /apollo-server-app/app/node_modules
    ports:
      - "4000:4000"
  elasticsearch:
    image: elasticsearch:7.8.1
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_PASSWORD: 'abc123'
  kibana:
    image: kibana:7.8.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601 