version: '2'
services:
  web:
    build: ./apollo-server-app
    command: npm run start
    volumes:
      - .:/apollo-server-app/app/
      - /apollo-server-app/app/node_modules
    ports:
      - "4000:4000"
  filebeat:
    build: ./filebeat
    container_name: filebeat
    user: root
    environment:
        - strict.perms=false
    volumes:
        - './filebeat/data:/usr/share/filebeat/data:rw'
        - './nginx/log:/var/log/nginx'    
  nginx:
    build: ./nginx
    volumes:
       - './nginx/log:/var/log/nginx'
    ports:
    - '80:80'
    depends_on:
    - web
  elasticsearch:
    image: elasticsearch:7.8.1
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_PASSWORD: 'abc123'
  kibana:
    image: kibana:7.8.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601 